spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${EC2_MYSQL_ADDRESS}/jookbiren?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${MYSQL_ROOT_NAME}
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    #    show-sql: true
    #    properties:
    #      hibernate:
    #        format_sql: true
    defer-datasource-initialization: true
  #  sql:
  #    init:
  #      mode: always
  config:
    import: aws-parameterstore:/web/jookbiren

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY}